version: "3.7"
services:
  php:
    build:
      context: ./images/php
      dockerfile: Dockerfile
      target: php_bothelp
    container_name: bothelp_php
    volumes:
      - ".:/var/www/bothelp"
      - "./log:/var/www/bothelp/log"
    networks:
      - bothelp_network
  nginx:
    ports:
      - "80:80"
      - "8080:80"
      - "443:443"
    build:
      context: ./images/nginx
      dockerfile: Dockerfile
      target: nginx_bothelp
    container_name: bothelp_nginx
    depends_on:
      - php
    networks:
      - bothelp_network
  redis:
    container_name: bothelp_redis
    image: redis:alpine
    command: ["sh", "-c", "exec redis-server"]
    volumes:
      - "./redis-data:/var/lib/redis"
    networks:
      - bothelp_network
networks:
  bothelp_network:
    driver: bridge