version: '3.1'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - app-network

  php:
    build:
      context: ./images/php
    links:
      - redis
    networks:
      - app-network

networks:
  app-network:
